import Head from "next/head";
import Link from 'next/link';
import Typical from "react-typical"
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
 AiFillFile,
 AiFillLinkedin,
 AiFillGithub,
 AiFillMail
} from 'react-icons/ai'
import { useState } from "react";


export default function Home() {
const [darkMode, setDarkMode]= useState(false);
return (
  <div className={darkMode? "dark" : ""}>
    <Head>
      <title>Nancy Luu Personal Website</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  
    <main className="bg-red-50 border-spacing border-t-60 border-b-60 border-l-60 border-r-60 border-emerald-700 dark:bg-emerald-700 dark:border-red-50">
      <section className ="min-h-full">
         <nav className="py-8 mb-48 flex justify-between font-titleFont2 text-emerald-700 dark:text-red-50">
         <Link href="/" legacyBehavior>
           <a className="text-xl px-16">developedbynancy</a>
          </Link>
          <ul className="flex items-center">
            <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl fill-emerald-700 dark:fill-white"/>
            </li>
            <li className="px-20">
              <Link href="/About" legacyBehavior>
              <a className="bg-white-500 px-4 dark:text-white text-xl">About</a>
              </Link>
            </li>
          </ul>
        </nav>
        <div className="dark:text-red-50 flex flex-col items-center justify-center font-titleFont2 text-emerald-700">
         <h1 className="text-6xl md:text-7xl">Nancy Luu</h1>
         <p className="text-xl md:text-2xl py-3 mdl:text-xl max-w-xl mx-auto dark:text-red-50 ">
           {' '}
      
           <Typical
             loop={1}
             wrapper="b"
             steps={[
               'Computer Science @ University of Houston',
               1000
             ]}
           
             />
         </p>
           
       </div>
       <div className="text-3xl md:text-4xl flex justify-center gap-5 py-1 mb-64 text-emerald-700 dark:text-white">
        <a href="/Resume-Nancy%20Luu.pdf" target="_blank" rel="noopener noreferrer" className="text-emerald-700 dark:text-white">
          <AiFillFile />
        </a>
        <a href="https://www.linkedin.com/in/nancyhluu/">
          <AiFillLinkedin/>
        </a>
        <a href="https://github.com/helloworldmynameisnancy">
          <AiFillGithub/>
        </a>
        <a href="mailto:n.luu1330@gmail.com">
          <AiFillMail/>
        </a>
       </div>
      </section>
    </main>
  </div>
);
};

 